version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - oracle
      - mongo
      - kafka
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
